---

 certbot_auto_renew: true
 certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
 certbot_auto_renew_hour: 2
 certbot_auto_renew_minute: 15
 certbot_auto_renew_options: "--quiet --no-self-upgrade"

 certbot_default_directory: /docker-data-nginx/conf.d/certbot
 certbot_create_if_missing: true
 certbot_create_method: standalone

 certbot_certs: 
  - email: stuart.milton@atos.net
    domains:
      - repo-hdws.nsandi.com
  - email: stuart.milton@atos.net
    domains:
      - build-hdws.nsandi.com
  - email: stuart.milton@atos.net
    domains:
      - quality-hdws.nsandi.com

 certbot_create_command: "certbot certonly --standalone --noninteractive --agree-tos --expand --config-dir '{{certbot_default_directory}}' --email {{ item.email }} -d {{ item.domains | join(',') }}"


