---

 - name: pull
   docker_image:
     name: "{{postgres_image_name}}"

 - name: Create dir
   file:
     path: "{{ item.split(':')[0] }}"
     state: directory
     recurse: yes
     owner: 1000
   with_items:
     - "{{ containers['postgres'].mounts }}"

 - name: Start postgres docker container
   docker_container:
     name: "postgres"
     image: "postgres"
     restart_policy: always
     ports: "{{ containers['postgres'].port_mappings }}"
     volumes: "{{ containers['postgres'].mounts }}"
     networks: 
       - name: ci_suite_network 
     env:
       POSTGRES_USER: "sonar"
       POSTGRES_PASSWORD: "sonar"

...

