---

 - name: pull
   docker_image:
     name: "{{nginx_image_name}}"

 - name: Ensure bind mount directories exist
   file:
     path: "{{ item.host_dir }}"
     state: directory
   with_items:
     - "{{nginx_mounts}}"

# Access mount by name (conf)
 - name: template in conf file
   template:
     src: templates/default.conf.j2
     dest: /docker-data-nginx/conf.d/default.conf

# Access network by name (ci)
 - name: Start nginx docker container
   docker_container:
     name: "nginx"
     image: "{{nginx_image_name}}"
     restart_policy: always
     restart: yes
     ports:
       - "80:80"
       - "443:443"
       - "18080:18080"
       - "18081:18081"
       - "19000:19000"
     volumes: 
       - "{{item.host_dir}}:{{item.container_dir}}"
     networks:
       - name: ci_suite_network 
   with_items:
     - "{{ nginx_mounts }}"

...

