---

 - name: pull
   docker_image:
     name: "{{sonarqube_image_name}}"

 - name: Create dir
   file:
     path: "{{ item.split(':')[0] }}"
     state: directory
     recurse: yes
     owner: 999
     group: 999
   with_items:
     - "{{ containers['sonarqube'].mounts }}"

 - name: Download Plugins
   get_url:
     url: https://github.com/felipebz/sonar-plsql/releases/download/2.2.0/sonar-plsql-open-plugin-2.2.0.jar
     dest: /docker-data-sonarqube/extensions/plugins/sonar-plsql-open-plugin-2.2.0.jar
     owner: 999
     group: 999
     timeout: 15

 - name: Start sonarqube docker container
   docker_container:
     name: "sonarqube"
     image: "{{sonarqube_image_name}}"
     restart_policy: always
     ports: "{{ containers['sonarqube'].port_mappings }}"
     volumes: "{{ containers['sonarqube'].mounts }}"
     networks:
       - name: ci_suite_network
     env:
       SONARQUBE_JDBC_USERNAME: "sonar"
       SONARQUBE_JDBC_PASSWORD: "sonar"
       SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"

...

