---

 - hosts: all
   become: true

   vars:
     CACommonName: "Ansible_CertAuth"
     CommonName: "ec2-35-178-130-116.eu-west-2.compute.amazonaws.com"

   tasks:
     - name: CA | Generate Private Key
       openssl_privatekey:
         path: "/tmp/{{ CACommonName }}.pem"
     - name: CA | Generate Certificate Signing Request
       shell: "openssl req -new -key /tmp/{{ CACommonName }}.pem -out /tmp/{{ CACommonName }}.csr -subj '/CN={{ CACommonName }}'"
     - name: CA | Generate Self Signed Certificate 
       shell: "openssl x509 -signkey /tmp/{{ CACommonName }}.pem -in /tmp/{{ CACommonName }}.csr -req -days 365 -out /tmp/{{ CACommonName }}.crt"

     - name: Child Cert| Generate Private Key
       openssl_privatekey:
         path: "/tmp/{{ CommonName }}.pem"
     - name: Child Cert | Generate Certificate Signing Request
       shell: "openssl req -new -key /tmp/{{ CommonName }}.pem -out /tmp/{{ CommonName }}.csr -subj '/CN={{ CommonName }}'"
     - name: Child Cert | Generate Self Signed Certificate
       shell: "openssl x509 -signkey /tmp/{{ CACommonName }}.pem -in /tmp/{{ CommonName }}.csr -req -days 365 -out /tmp/{{ CommonName }}.crt"





#     - openssl_privatekey:
#         path: /tmp/child.com.pem
#     - openssl_csr:
#         path: /tmp/child.com.csr
#         privatekey_path: /tmp/child.com.pem
#         common_name: child.com
#     - openssl_certificate:
#         path: /tmp/child.com.crt
#         privatekey_path: /tmp/ansible.com.pem
#         csr_path: /tmp/child.com.csr
#         provider: selfsigned 
