---

 - hosts: all
   become: true

   tasks:
   - name: pull
     docker_image:
       name: sonatype/nexus3

   - name: create volume
     docker_volume:
       name: nexus-data-test

   - name: Start nexus docker container
     docker_container:
       name: "nexus3"
       image: "sonatype/nexus3"
       restart_policy: always
       ports:
         - "8081:8081"
         - "5000:5000"
       volumes: 
         - nexus-data-test:/nexus-data-test

# build oracle image again
# push oracle image to nexus
# run oracle container - volume?
# run sql command against DB Server
# 

...
