---

 docker_networks:
   - "ci_suite_network"

 firewall_ports:
   - { service: ssh, state: enabled }
   - { service: http, state: enabled }
   - { service: https, state: enabled }
   - { port: 18080,  proto: tcp, state: enabled }
   - { port: 18081,  proto: tcp, state: enabled }
   - { port: 19000,  proto: tcp, state: enabled }
   - { port: 18083,  proto: tcp, state: enabled }

 containers:
   jenkins:
     mounts:
       - /docker-data-jenkins:/var/jenkins_home
       - /docker-data-oracle/oradata:/tmp/oradata
       - /docker-data-oracle-reference/oradata:/tmp/oradataref
       - /docker-data-python:/tmp/python
     mount_files:
       - /var/run/docker.sock:/var/run/docker.sock
     all_mounts:
       - /docker-data-jenkins:/var/jenkins_home
       - /docker-data-oracle/oradata:/tmp/oradata
       - /docker-data-oracle-reference/oradata:/tmp/oradataref
       - /docker-data-python:/tmp/python
       - /var/run/docker.sock:/var/run/docker.sock
     port_mappings:
       - "8080:8080"
       - "50000:50000"
   nginx:
     mounts:
       - /docker-data-nginx/conf.d:/etc/nginx/conf.d
     port_mappings:
       - "443:443"
       - "18080:18080"
       - "18081:18081"
       - "19000:19000"
   nexus:
     mounts:
       - /docker-data-nexus:/nexus-data
     port_mappings:
       - "8081:8081"
       - "5000:5000"
   oracle:
     mounts:
       - /docker-data-oracle:/ORCL
     port_mappings:
       - "1521:1521"
       - "5500:5500"
   postgres:
     mounts:
       - /docker-data-postgres:/var/lib/postgresql/data
     port_mappings:
       - "5432:5432"
   sonarqube:
     mounts:
       - /docker-data-sonarqube/conf:/opt/sonarqube/conf
       - /docker-data-sonarqube/data:/opt/sonarqube/data
       - /docker-data-sonarqube/logs:/opt/sonarqube/logs
       - /docker-data-sonarqube/extensions/plugins:/opt/sonarqube/extensions
     port_mappings:
       - "9000:9000"


 nginx_image_name: "nginx"
 nexus_image_name: "sonatype/nexus3"
 oracle_image_name: "store/oracle/database-enterprise:12.2.0.1"
 postgres_image_name: "postgres"
 sonarqube_image_name: "sonarqube"

 jenkins_image_name: "jenkins-docker" #"jenkins/jenkins"
 jenkins_admin_username: "{{ jenkins_username }}"
 jenkins_admin_password: "{{ jenkins_password }}"

 all_file_system_mounts:
   - "{{jenkins_mounts}}"
   - "{{nexus_mounts}}"
   - "{{nexus_mounts}}"
   - "{{oracle_mounts}}"
   - "{{postgres_mounts}}"

 enable_certbot_repos:
  - "rhui-REGION-rhel-server-extras"
  - "rhui-REGION-rhel-server-optional"


...
