---

 nginx_site_config:
   jenkins:
     application_name: jenkins
     listening_dns: localhost 
     listening_port: 18080
     downstream_server_ip: jenkins
     downstream_server_port: 8080
     location_config:
        - "proxy_set_header        Host $host:$server_port;"
        - "proxy_set_header        X-Real-IP $remote_addr;"
        - "proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;"
        - "proxy_set_header        X-Forwarded-Proto $scheme;"
        - "proxy_read_timeout      90;"

...
