---

 - name: pull
   docker_image:
     name: "{{nexus_image_name}}"

 - name: Ensure Nexus bind mount directories exist
   file:
     path: "{{ item }}"
     state: directory
     recurse: yes
     owner: 200
   with_items:
     - /nexus-data

 - name: Start nexus docker container
   docker_container:
     name: "nexus3"
     image: "{{nexus_image_name}}"
     restart_policy: always
     ports:
       - "8081:8081"
       - "5000:5000"
     volumes: 
       - /nexus-data:/nexus-data

...

