---

 - name: pull
   docker_image:
     name: "{{nexus_image_name}}"

 - name: Ensure Nexus bind mount directories exist
   file:
     path: "{{ item.split(':')[0] }}"
     state: directory
     recurse: yes
     owner: 200
   with_items:
     - "{{ containers['nexus'].mounts }}"

 - name: Start nexus docker container
   docker_container:
     name: "nexus3"
     image: "{{nexus_image_name}}"
     restart_policy: always
     restart: yes
     ports: "{{containers['nexus'].port_mappings}}"
     volumes: "{{containers['nexus'].mounts}}"

...

