---

# Should remove my personal details from here
 - name: Login to Docker Hub
   docker_login:
     username: "{{ docker_repo_username }}"
     password: "{{ docker_repo_password }}" 

 - name: pull
   docker_image:
     name: "{{oracle_image_name}}"

 - name: Ensure bind mount directories exist
   file:
     path: "{{ item.split(':')[0] }}"
     state: directory
#     resurse: yes
     owner: 54321
   with_items:
     - "{{ containers['oracle'].mounts }}"

 - name: Start oracle docker container
   docker_container:
     name: "oracle12ee"
     image: "{{oracle_image_name}}" 
     restart_policy: always
     ports: "{{ containers['oracle'].port_mappings }}"
     volumes: "{{ containers['oracle'].mounts }}"
 
...

