---

 application_name: default

 listening_dns: default.website.com
 listening_port: 80

 downstream_server_ip: 99.99.99.99
 downstream_server_port: 8080

 location_config: ""
 server_config: ""
 
...
