---

---

 - name: Build an image and push it to a private repo
   docker_image:
     path: "{{ role_path }}/files/docker"
     name: jenkins-docker
     state: present
     force: true


 - name: Ensure Jenkins bind mount directories exist
   file:
     path: "{{ item.split(':')[0] }}/init.groovy.d"
     state: directory
     recurse: yes
     owner: 1000
   with_items:
     - "{{ containers['jenkins'].mounts }}"

 - name: Ensure Jenkins Docker mount exist
   file:
     path: "{{ item.split(':')[0] }}"
     state: file
     owner: 1000
   with_items:
     - "{{ containers['jenkins'].mount_files }}"


 - name: Start jenkins docker container
   docker_container:
     name: "jenkins"
     image: jenkins-docker 
     restart_policy: always
     restart: yes
     ports: "{{containers['jenkins'].port_mappings}}"
     volumes: "{{ containers['jenkins'].all_mounts }}"
     networks:
     - name: ci_suite_network

 - name: configure default users
   template:
     src: basic-security.groovy.j2
     dest: "{{ item.split(':')[0] }}/init.groovy.d/basic-security.groovy"
     owner: 1000
     mode: 0775
   with_items:
     - "{{ containers['jenkins'].mounts }}"

...
