---

 - name: pull
   docker_image:
     name: "{{jenkins_image_name}}"

 - name: Ensure Jenkins bind mount directories exist
   file:
     path: "{{ item.split(':')[0] }}"
     state: directory
     recurse: yes
     owner: 1000
   with_items:
     - "{{ containers['jenkins'].mounts }}"

 - name: Start jenkins docker container
   docker_container:
     name: "jenkins"
     image: "{{jenkins_image_name}}"
     restart_policy: always
     restart: yes
     ports: "{{containers['jenkins'].port_mappings}}"
     volumes: "{{ containers['jenkins'].mounts }}"

...

